### ISSUE TITLE
Services alerting

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/platform-reports#537]
This would be great if we utilize the Prometheus alert manager to notify us if something goes wrong with our services or their resources.
For instance:
- monitor disk usage for Metrics gathering ([example](https://neuromation.slack.com/archives/CE9SZE5B3/p1650012174783679) issue)
- monitor storage API restarts (we had issues with storage API restarts due to failed health checks)
- etc
wdyt?

**Comment by asvetlov** [comment]
The feature request should land on the platform-reports, not platform-monitoring
