### ISSUE TITLE
Add cluster label to all metrics

### ISSUE THREAD

**Issue by dalazx** [neuro-inc/platform-reports#621]

**Comment by YevheniiSemendiak** [comment]
This is done for `cpu_min/max, co2` metrics here https://github.com/neuro-inc/platform-reports/commit/a31cc483e3c86b48bd25a1889ff3725458d6ea13#diff-eb87e8daf04814c0daf5dfe932d6fbe0089a5cb93e603659a1572a197c01c93dR145-R151
But I'll keep this task to expose https://github.com/neuro-inc/platform-config/issues/1377 via node-exporter, correct @dalazx ?
